$('.ad').remove();
$('.c5.classifieds.cfix').remove();
$('.fN-affiliateStrip').remove();
$('.strapHeadingDealPartner, .cN-storyDeal').remove();
$('.cT-featuredNews').remove();
$('.fN-mostViewed').remove();
$('.iframeMozo').remove();
$('.cA-gutter').remove();
$('div[data-jobsbrand]').hide();
$('#comments').hide();
$('.cN-storyCommentLatest').hide();
